<?
$aMenuLinks = Array(
    Array(
        "CART",
        "/test/index.php",
        Array(),
        Array(
            "CLASS"=>"cart-nav",
            "IMG_SRC"=>"/local/templates/My_template/assets/img/core-img/cart.png",
        ),
        ""
    ),
    Array(
        "FAVORITE",
        "/test/index.php",
        Array(),
        Array(
            "CLASS"=>"fav-nav",
            "IMG_SRC"=>"/local/templates/My_template/assets/img/core-img/favorites.png",
        ),
        ""
    ),
    Array(
        "SEARCH",
        "/test/index.php",
        Array(),
        Array(
            "CLASS"=>"search-nav",
            "IMG_SRC"=>"/local/templates/My_template/assets/img/core-img/search.png",
        ),
        ""
    ),
);
?>